version: "3.7"

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "bot_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data:cached

#  redis:
#    container_name: redis
#    image: redis:6.2-alpine


volumes:
  db_data:
